version: '2.2'
services:
    logstash:
      image: docker.io/elastic/logstash:7.10.2
      container_name: logstash
      environment:
        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      depends_on:
        - elasticsearch
      ports:
        - "5044:5044/udp"
      volumes:
        - ./deploy/logstash.conf:/config/logstash.conf:ro
      command: logstash -f /config/logstash.conf
      networks:
        - logging
        - ugc

    elasticsearch:
      image: docker.io/elastic/elasticsearch:7.10.2
      container_name: elasticsearch
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      # ports:
      #   - 9200:9200
      volumes:
        - es_logs:/es_logs/data
      restart: always
      networks:
        - logging

    kibana:
      image: docker.io/elastic/kibana:7.10.2
      container_name: kibana
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
        - elasticsearch
      networks:
        - logging

volumes:
  es_logs:

networks:
  ugc:
    driver: bridge
  logging:
    driver: bridge