---
version: '2'
services:
  broker:
    image: confluentinc/cp-server:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    restart: always

  ugc_api:
    build: ./ugc_api
    container_name: ugc_api
    env_file:
      - .env
    environment:
      - KAFKA_URL=broker:29092
    depends_on:
      - broker
    ports:
      - '8000:8000'

  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./db/clickhouse/data/node1:/etc/clickhouse-server
      - ./db/clickhouse/data/shard_1:/docker-entrypoint-initdb.d/
    depends_on:
      - zookeeper

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./db/clickhouse/data/node2:/etc/clickhouse-server
      - ./db/clickhouse/data/replica_2_4:/docker-entrypoint-initdb.d/
    depends_on:
      - zookeeper

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./db/clickhouse/data/node3:/etc/clickhouse-server
      - ./db/clickhouse/data/shard_3:/docker-entrypoint-initdb.d/
    depends_on:
      - zookeeper

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./db/clickhouse/data/node4:/etc/clickhouse-server
      - ./db/clickhouse/data/replica_2_4:/docker-entrypoint-initdb.d/
    depends_on:
      - zookeeper
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mo_data:/mo_data

  logstash:
      image: logstash:7.10.1
      environment:
        XPACK_MONITORING_ENABLED: "false"
        ES_HOST: "elasticsearch:9200"
      depends_on:
        - elasticsearch
      ports:
        - "5044:5044/udp"
      volumes:
        - ./deploy/logstash.conf:/config/logstash.conf:ro
        - /tmp/logs/nginx/:/var/log/nginx/:ro
      command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ports:
      - 9200:9200
    volumes:
      - es_logs:/es_logs/data
    restart: always

  kibana:
      image: kibana:7.10.1
      ports:
        - "5601:5601"
      environment:
        - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      depends_on:
        - elasticsearch

  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/configs:/etc/nginx/conf.d:ro
      - /tmp/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: nginx 
    restart: always
    depends_on:
        - ugc_api

volumes:
  mo_data:
  es_logs: