POST http://127.0.0.1:8000/api/v1/bookmark/
Content-Type: application/json

{
    "user_id": "5002717",
    "movie_id": "tt01203318"
}
###
GET http://127.0.0.1:8000/api/v1/bookmark/63f08150a91df04573fe4e28
###
GET http://127.0.0.1:8000/api/v1/bookmark/list/5002717
###
DELETE http://127.0.0.1:8000/api/v1/bookmark/
Content-Type: application/json

{
    "user_id": "5002717",
    "movie_id": "tt01203318"
}