# Generated by Django 4.1.2 on 2022-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_filmwork_type_alter_personfilmwork_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('genre', 'film_work'), name='unique_genre_filmwork'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('role', 'person', 'film_work'), name='unique_role_person_filmwork'),
        ),
    ]
