name: UGC+ application

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    
jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install mypy
        pip install -r ./requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 ./ugc_api --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Lint with mypy
      run: |
        mypy ugc_api/ --ignore-missing-imports --disable-error-code attr-defined --disable-error-code misc --disable-error-code arg-type

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    needs: tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub Backend
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ugc_api/
          tags: ${{ secrets.DOCKER_USERNAME }}/ugc_api:latest

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
