name: Python application

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install mypy
        pip install -r ./requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./ugc_api --exit-zero --format=html --htmldir=reports/api/wemake-python-styleguide/

    - name: Lint with mypy
      run: |
        mypy --html-report reports/api/mypy/ ugc_api/* || true
